name: StaffChat
main: Thunder33345\StaffChat\StaffChat
version: "1.1.2"
api: [4.0.0]
author: Thunder33345
website: "https://github.com/ThunderDoesPlugins/StaffChat"
description: "Private Staff Chat Plugin"

permissions:
  staffchat.command:
    default: op
    description: "Use the staff chat command"
  staffchat.read:
    default: op
    description: "Read from staff chat"
  staffchat.chat:
    default: op
    description: "Chat into staff chat"
  staffchat.attach:
    default: op
    description: "Attach console into staff chat"
  staffchat.check:
    default: op
    description: "Check other players status"
  staffchat.list:
    default: op
    description: "Show info list of players"
  staffchat.reload:
    default: false
    description: "Reload staff chat internal data"